FROM python:3.9
MAINTAINER Benedikt Kristinsson <ben@lokun.is>

ENV TZ=UTC
ENV DEBIAN_FRONTEND=noninteractive
ENV TERM=xterm-256color
# ENV PIP_ROOT_USER_ACTION=ignore
# can also use `pip install --root-user-action=ignore`
