---

# - name: get list of existing groups
#   shell: "/usr/bin/getent group | awk -F':' '{print $1}'"
#   register: etc_groups
#   check_mode: false
#   changed_when: false
#   tags: users
#
# use with:
#
#  with_items: "{{ systemuserlist.telegraf.groups }}"
#  when: 'item in etc_groups.stdout_lines'
- name: group for telegraf user
  group:
    state: present
    name: "{{ systemuserlist.telegraf.username }}"
    gid: "{{ systemuserlist.telegraf.gid }}"
  tags: users
  notify: restart telegraf

- name: telegraf user
  user:
    state: present
    name: "{{ systemuserlist.telegraf.username }}"
    group: "{{ systemuserlist.telegraf.username }}"
    shell: "{{ systemuserlist.telegraf.shell }}"
    uid: "{{ systemuserlist.telegraf.uid }}"
    create_home: true
    home: "{{ systemuserlist.telegraf.home }}"
    move_home: true
    system: true
  tags: users
  notify: restart telegraf

- name: allow telegraf to sudo and use smartctl
  template:
    src: telegraf.sudoers.j2
    dest: /etc/sudoers.d/telegraf
    mode: 0440
    owner: root
    group: root
  when: telegraf_smart_disks
  notify: restart telegraf
  tags: users

- name: install virtualenv with packages
  pip:
    name: "{{item}}"
    state: present
    virtualenv: "{{telegraf_venv_path}}"
    virtualenv_site_packages: false
    virtualenv_command: python3 -m venv
  when: not ansible_check_mode
  loop:
    - humanize
  loop_control:
    label: "{{item}}"
  tags:
    - common-telegraf-virtualenv
    - venvs
    - virtualenvs
    - pip
    - packages

- name: copy scripts
  copy:
    src: "{{item}}"
    dest: "/usr/local/bin/telegraf-vnstat.py"
    mode: 0775
    owner: telegraf
    group: telegraf
  notify: restart telegraf
  loop:
    - "telegraf-vnstat.py"
  loop_control:
    label: "{{item}}"

# Clean up old keys for influxdata repo
- name: clean up repo keys (+virtualenv in wrong path) with invalid names or paths
  file:
    state: absent
    path: "{{ item }}"
  diff: false
  loop_control:
    label: "{{ item }}"
  with_items:
    # Wrong/old/incorrect path for virtualenv
    - /var/lib/virtualenvs/telegraf-scripts/
    # 2024 key (now 'influxdb-archive-keyring-2024.asc')
    - /usr/share/keyrings/influxdb-archive-keyring.gpg
    - /usr/share/keyrings/influxdb-archive-keyring.asc

# Clean up files in '/etc/apt/sources.d/' generated by the 'apt_repository' module
- name: cleanup repos.d files
  file:
    path: "/etc/apt/sources.list.d/{{ item }}"
    state: absent
  loop_control:
    label: "{{ item }}"
  with_items:
    - repos_influxdata_com_debian.list
    - repos_influxdata_com_ubuntu.list
    - repos_influxdata_com_raspbian.list

#- name: get influxdb key
#  get_url:
#    url:  https://repos.influxdata.com/influxdb-archive.key
#    dest: /etc/apt/trusted.gpg.d/influxdb-archive.asc

# wget https://repos.influxdata.com/influxdata-archive.key
# mv influxdata-archive.key influxdata-archive.asc
- name: copy ascii-armored influxdb key
  copy:
    src: "{{item}}"
    dest: "/usr/share/keyrings/{{item}}"
    owner: root
    group: root
    mode: '0644'
  diff: false
  loop:
    - "influxdata-archive.asc"
  loop_control:
    label: "{{item}}"
  tags:
    - influx-repo
    - packages

# Uses '/etc/apt/sources.list.d/repos_influxdata_com_ubuntu.list'
# Manages entries separately, so changed/different/invalid entries remain unless
# they are specifically removed with 'state: absent' and a matching 'repo:' arg.
#
# Cons:
#  - Existing entries need to be removed explicitly
# Pros:
#  - Updates apt cache without a needing a separate task
#
#- name: "add repo"
#  ansible.builtin.apt_repository:
#    repo: "deb [signed-by=/usr/share/keyrings/influxdb-archive-keyring.asc] https://repos.influxdata.com/{{ansible_distribution|lower}} stable main"
#    codename: stable
#    state: present
#    update_cache: true

- name: add influxdata repo
  template:
    src: "{{item}}.j2"
    dest: "/etc/apt/sources.list.d/{{item}}"
    mode: "0644"
    owner: root
    group: root
  loop:
    - "influxdata.list"
  loop_control:
    label: "{{item}}"
  register: influxdata_repo
  tags:
    - packages
    - influx-repo

- name: install latest packages
  apt:
    name:
      - telegraf
      # telegraf errors and doesnt do the smart check if this
      # isnt installed, regardless of if there are nvme disks
      - nvme-cli
    state: latest
    update_cache: |
      {{influxdata_repo.changed}}
  tags:
    - packages
    - influx-repo
  notify: restart telegraf

- name: template config
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  notify:
    - restart telegraf
  tags:
    - telegraf-config
    - telegraf.conf

- name: start and enable service
  service:
    name: telegraf
    state: started
    enabled: true
  notify: restart telegraf
